# Copyright 2021 Ubuntu
# See LICENSE file for licensing details.
#

options:
  thing:
    default: ğŸ
    description: A thing used by the charm.
    type: string
  port:
    default: 80
    description: Nginx port
    type: int
