# Copyright 2021 Ubuntu
# See LICENSE file for licensing details.
#

options:
  thing:
    default: ğŸ
    description: A thing used by the charm.
    type: string
  my-config-option:
    default: this-is-a-default-value
    description: My config option.
    type: string
